version: '3'
services:
    api_server:
        build: .
        ports:
            - "${PORT}:${PORT}"
        volumes:
            - .:/usr/src/app
        depends_on:
            - postgres_db
        environment:
            DB_HOST: postgres_db

    postgres_db:
        image: postgres
        environment:
            POSTGRES_DB: ${DB}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres:/data/postgres

    pgadmin:
        image: dpage/pgadmin4
        depends_on: 
            - postgres_db
        environment:
            PGADMIN_DEFAULT_EMAIL: "bd_proj@bd.com"
            PGADMIN_DEFAULT_PASSWORD: "pgadmin"
        volumes:
            - pgadmin:/root/pgadmin
        ports:
            - "${PGADMIN_PORT}:80"

volumes:
    postgres:
    pgadmin:
